"""
This type stub file was generated by pyright.
"""

import logging
from logging import NullHandler

from consulate.client import Consul
from consulate.exceptions import (
    ACLDisabled,
    ClientError,
    ConsulateException,
    Forbidden,
    LockFailure,
    NotFound,
    RequestError,
    ServerError,
)

"""
Consulate: A client library for Consul

"""
__version__ = ...
__all__ = [
    "__version__",
    "Consul",
    "ConsulateException",
    "ClientError",
    "ServerError",
    "ACLDisabled",
    "Forbidden",
    "NotFound",
    "LockFailure",
    "RequestError",
]
