"""
This type stub file was generated by pyright.
"""

"""
HTTP Client Library Adapters

"""
LOGGER = ...
CONTENT_FORM = ...
CONTENT_JSON = ...

def prepare_data(fun) -> Callable[..., Any]:
    """Decorator for transforming the data being submitted to Consul

    :param function fun: The decorated function

    """
    ...

class Request:
    """The Request adapter class"""
    def __init__(self, timeout=..., verify=..., cert=...) -> None:
        """
        Create a new request adapter instance.

        :param int timeout: [optional] timeout to use while sending requests
            to consul.
        """
        ...

    def delete(self, uri) -> Response:
        """Perform a HTTP delete

        :param src uri: The URL to send the DELETE to
        :rtype: consulate.api.Response

        """
        ...

    def get(self, uri, timeout=...) -> Response:
        """Perform a HTTP get

        :param src uri: The URL to send the DELETE to
        :param timeout: How long to wait on the response
        :type timeout: int or float or None
        :rtype: consulate.api.Response

        """
        ...

    def get_stream(self, uri) -> Generator[str, Any, None]:
        """Perform a HTTP get that returns the response as a stream.

        :param src uri: The URL to send the DELETE to
        :rtype: iterator

        """
        ...

    @prepare_data
    def put(self, uri, data=..., timeout=...) -> Response:
        """Perform a HTTP put

        :param src uri: The URL to send the DELETE to
        :param str data: The PUT data
        :param timeout: How long to wait on the response
        :type timeout: int or float or None
        :rtype: consulate.api.Response

        """
        ...

class UnixSocketRequest(Request):
    """Use to communicate with Consul over a Unix socket"""
    def __init__(self, timeout=...) -> None: ...
