"""
This type stub file was generated by pyright.
"""

"""Consulate CLI commands"""
CONSUL_ENV_VAR = ...
EPILOG = ...

def on_error(message, exit_code=...):
    """Write out the specified message to stderr and exit the specified
    exit code, defaulting to ``2``.

    :param str message: The exit message
    :param int exit_code: The numeric exit code

    """
    ...

def connection_error() -> None:
    """Common exit routine when consulate can't connect to Consul"""
    ...

ACL_PARSERS = ...
KV_PARSERS = ...

def add_acl_args(parser) -> None:
    """Add the acl command and arguments.

    :param argparse.Subparser parser: parser

    """
    ...

def add_kv_args(parser) -> None:
    """Add the kv command and arguments.

    :param argparse.Subparser parser: parser

    """
    ...

def add_register_args(parser) -> None:
    """Add the register command and arguments.

    :param argparse.Subparser parser: parser

    """
    ...

def add_run_once_args(parser) -> None:
    """Add the run_once command and arguments.

    :param argparse.Subparser parser: parser

    """
    ...

def add_deregister_args(parser) -> None:
    """Add the deregister command and arguments.

    :param argparse.Subparser parser: parser

    """
    ...

def add_services_args(parser) -> None:
    """Add the services command and arguments.

    :param argparse.Subparser parser: parser

    """
    ...

def parse_cli_args() -> Namespace:
    """Create the argument parser and add the arguments"""
    ...

def acl_backup(consul, args) -> None:
    """Dump the ACLs from Consul to JSON

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def acl_restore(consul, args) -> None:
    """Restore the Consul KV store

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

ACL_ACTIONS = ...

def kv_backup(consul, args) -> None:
    """Backup the Consul KV database

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def kv_delete(consul, args) -> None:
    """Remove a key from the Consulate database

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def kv_get(consul, args) -> None:
    """Get the value of a key from the Consul database

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def kv_ls(consul, args) -> None:
    """List out the keys from the Consul KV database

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def kv_mkdir(consul, args) -> None:
    """Make a key based path/directory in the KV database

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def kv_restore(consul, args) -> None:
    """Restore the Consul KV store

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def kv_rm(consul, args) -> None:
    """Remove a key from the Consulate database

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def kv_set(consul, args) -> None:
    """Set a value of a key int the Consul database

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

KV_ACTIONS = ...

def register(consul, args) -> None:
    """Handle service registration.

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def deregister(consul, args) -> None:
    """Handle service deregistration.

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def run_once(consul, args) -> None:
    """Ensure only one process can run a command at a time

    :param consulate.api_old.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def services(consul, args) -> None:
    """Dump the list of services registered with Consul

    :param consulate.api.Consul consul: The Consul instance
    :param argparser.namespace args: The cli args

    """
    ...

def main() -> None:
    """Entrypoint for the consulate cli application"""
    ...
