"""
This type stub file was generated by pyright.
"""

"""
Misc utility functions and constants

"""
DURATION_PATTERN = ...
PYTHON3 = ...

def is_string(value) -> bool:
    """Python 2 & 3 safe way to check if a value is either an instance of str
    or unicode.

    :param mixed value: The value to evaluate
    :rtype: bool

    """
    ...

def maybe_encode(value):
    """If the value passed in is a str, encode it as UTF-8 bytes for Python 3

    :param str|bytes value: The value to maybe encode
    :rtype: bytes

    """
    ...

def response_ok(response, raise_on_404=...) -> bool:
    """Evaluate the HTTP response and raise the appropriate exception if
    required.

    :param requests.response response: The HTTP response
    :param bool raise_on_404: Raise an exception on 404 error
    :rtype: bool
    :raises: consulate.exceptions.ConsulateException

    """
    ...

def validate_go_interval(value, _model=...) -> bool:
    """Validate the value passed in returning :data:`True` if it is a Go
    Duration value.

    :param str value: The string to check
    :param consulate.models.base.Model _model: Optional model passed in
    :rtype: bool

    """
    ...

def validate_url(value, _model=...):
    """Validate that the value passed in is a URL, returning :data:`True` if
    it is.

    :param str value: The string to check
    :param consulate.models.base.Model _model: Optional model passed in
    :rtype: bool

    """
    ...
