"""
This type stub file was generated by pyright.
"""

from consulate.models import base

"""Models for the ACL endpoints"""

class ACLPolicy(base.Model):
    """Defines the model used for an ACL policy."""

    __slots__ = ...
    __attributes__ = ...

class ACLRole(base.Model):
    """Defines the model used for an ACL role."""

    __slots__ = ...
    __attributes__ = ...

class ACLToken(base.Model):
    """Defines the model used for an ACL token."""

    __slots__ = ...
    __attributes__ = ...

class ACL(base.Model):
    """Defines the model used for an individual ACL token."""

    __slots__ = ...
    __attributes__ = ...
