"""
This type stub file was generated by pyright.
"""

from consulate.models import base

"""Models for the Agent endpoints"""

class Check(base.Model):
    """Model for making Check API requests to Consul."""

    __slots__ = ...
    __attributes__ = ...
    def __init__(self, **kwargs) -> None: ...

class Service(base.Model):
    """Model for making Check API requests to Consul."""

    __slots__ = ...
    __attributes__ = ...
