"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable

"""
Base Model

"""

class Model(Iterable):
    """A model contains an __attribute__ map that defines the name,
    its type for type validation, an optional validation method, a method
    used to

    .. python::

        class MyModel(Model):

            __attributes__ = {
                'ID': {
                    'type': uuid.UUID,
                    'required': False,
                    'default': None,
                    'cast_from': str,
                    'cast_to': str
                },
                'Serial': {
                    'type': int
                    'required': True,
                    'default': 0,
                    'validator': lambda v: v >= 0 end,
                }
            }

    """

    __attributes__ = ...
    def __init__(self, **kwargs) -> None: ...
    def __iter__(self) -> Generator[tuple[Any, Any], Any, None]:
        """Iterate through the model's key, value pairs.

        :rtype: iterator

        """
        ...

    def __setattr__(self, name, value) -> None:
        """Set the value for an attribute of the model, validating the
        attribute name and its type if the type is defined in ``__types__``.

        :param str name: The attribute name
        :param mixed value: The value to set
        :raises: AttributeError
        :raises: TypeError
        :raises: ValueError

        """
        ...

    def __getattribute__(self, name) -> Any:
        """Return the attribute from the model if it is set, otherwise
        returning the default if one is set.

        :param str name: The attribute name
        :rtype: mixed

        """
        ...
