# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-private-key
        exclude: "(bootstrap-vagrant.sh|manifests/default.pp)"

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

# disabled because of a dependency glitch and we can't update as we're still
# on python 2, will be fixed when switching to nautilus
#-   repo: https://github.com/psf/black
#    rev: 21.12b0
#    hooks:
#   -   id: black
