"""
This type stub file was generated by pyright.
"""

"""
Base Endpoint class used by all endpoint classes

"""

class Endpoint:
    """Base class for API endpoints"""

    KEYWORD = ...
    def __init__(self, uri, adapter, datacenter=..., token=...) -> None:
        """Create a new instance of the Endpoint class

        :param str uri: Base URI
        :param consul.adapters.Request adapter: Request adapter
        :param str datacenter: datacenter
        :param str token: Access Token

        """
        ...

class Response:
    """Used to process and wrap the responses from Consul.

    :param int status_code: HTTP Status code
    :param str body: The response body
    :param dict headers: Response headers

    """

    status_code = ...
    body = ...
    headers = ...
    def __init__(self, response) -> None:
        """Create a new instance of the Response class.

        :param requests.response response: The requests response

        """
        ...
