"""
This type stub file was generated by pyright.
"""

from consulate.api import base

"""
Consul Coordinate Endpoint Access

"""

class Coordinate(base.Endpoint):
    """Used to query node coordinates."""
    def node(self, node_id) -> list[Any]:
        """Return coordinates for the given node.

        :param str node_id: The node ID
        :rtype: dict

        """
        ...

    def nodes(self) -> list[dict[Any, Any]] | list[Any]:
        """Return coordinates for the current datacenter.

        :rtype: list

        """
        ...

    def rtt(self, src, dst):
        """Calculated RTT between two node coordinates.

        :param dict src
        :param dict dst
        :rtype float

        """
        ...
