"""
This type stub file was generated by pyright.
"""

from consulate.api import base

"""
Consul Event Endpoint Access

"""

class Event(base.Endpoint):
    """The Event endpoints are used to fire a new event and list recent events."""
    def fire(
        self, name, payload=..., datacenter=..., node=..., service=..., tag=...
    ):
        """Trigger a new user Event

        :param str name: The name of the event
        :param str payload: The opaque event payload
        :param str datacenter: Optional datacenter to fire the event in
        :param str node: Optional node to fire the event for
        :param str service: Optional service to fire the event for
        :param str tag: Option tag to fire the event for
        :return str: the new event ID

        """
        ...

    def list(self, name=...) -> list[Any]:
        """Returns the most recent events known by the agent. As a consequence
        of how the event command works, each agent may have a different view of
        the events. Events are broadcast using the gossip protocol, so they
        have no global ordering nor do they make a promise of delivery.

        :return: list

        """
        ...
