"""
This type stub file was generated by pyright.
"""

from typing import Any

from consulate.api import base

"""
Consul Health Endpoint Access

"""

class Health(base.Endpoint):
    """Used to query health related information. It is provided separately
    from the Catalog, since users may prefer to not use the health checking
    mechanisms as they are totally optional. Additionally, some of the query
    results from the Health system are filtered, while the Catalog endpoints
    provide the raw entries.

    """
    def checks(
        self, service_id, node_meta=...
    ) -> list[dict[Any, Any]] | list[Any]:
        """Return checks for the given service.

        :param str service_id: The service ID
        :param str node_meta: Filter checks using node metadata
        :rtype: list

        """
        ...

    def node(self, node_id) -> list[dict[Any, Any]] | list[Any]:
        """Return the health info for a given node.

        :param str node_id: The node ID
        :rtype: list

        """
        ...

    def service(
        self,
        service_id: str,
        tag: Any = ...,
        passing: Any = ...,
        node_meta: Any = ...,
    ) -> list[dict[str, Any]]:
        """Returns the nodes and health info of a service

        :param str service_id: The service ID
        :param str node_meta: Filter services using node metadata
        :rtype: list

        """
        ...

    def state(self, state) -> list[dict[Any, Any]] | lisst[Any]:
        """Returns the checks in a given state where state is one of
        "unknown", "passing", "warning", or "critical".

        :param str state: The state to get checks for
        :rtype: list

        """
        ...
