"""
This type stub file was generated by pyright.
"""

from consulate.api import base

"""
Consul KV Endpoint Access

"""

class KV(base.Endpoint):
    """The :py:class:`consul.api.KV` class implements a :py:class:`dict` like
    interface for working with the Key/Value service. Simply use items on the
    :py:class:`consulate.Session` like you would with a :py:class:`dict` to
    :py:meth:`get <consulate.api.KV.get>`,
    :py:meth:`set <consulate.api.KV.set>`, or
    :py:meth:`delete <consulate.api.KV.delete>` values in the key/value store.

    Additionally, :py:class:`KV <consulate.api.KV>` acts as an
    :py:meth:`iterator <consulate.api.KV.__iter__>`, providing methods to
    iterate over :py:meth:`keys <consulate.api.KV.keys>`,
    :py:meth:`values <consulate.api.KV.values>`,
    :py:meth:`keys and values <consulate.api.KV.iteritems>`, etc.

    Should you need access to get or set the flag value, the
    :py:meth:`get_record <consulate.api.KV.get_record>`,
    :py:meth:`set_record <consulate.api.KV.set_record>`,
    and :py:meth:`records <consulate.api.KV.records>` provide a way to access
    the additional fields exposed by the KV service.

    """
    def __contains__(self, item) -> bool:
        """Return True if there is a value set in the Key/Value service for the
        given key.

        :param str item: The key to check for
        :rtype: bool

        """
        ...

    def __delitem__(self, item) -> None:
        """Delete an item from the Key/Value service

        :param str item: The key name

        """
        ...

    def __getitem__(self, item):
        """Get a value from the Key/Value service, returning it fully
        decoded if possible.

        :param str item: The item name
        :rtype: mixed
        :raises: KeyError

        """
        ...

    def __iter__(self) -> Generator[Any, Any, None]:
        """Iterate over all the keys in the Key/Value service

        :rtype: iterator

        """
        ...

    def __len__(self) -> int:
        """Return the number if items in the Key/Value service

        :return: int

        """
        ...

    def __setitem__(self, item, value) -> None:
        """Set a value in the Key/Value service, using the CAS mechanism
        to ensure that the set is atomic. If the value passed in is not a
        string, an attempt will be made to JSON encode the value prior to
        setting it.

        :param str item: The key to set
        :param mixed value: The value to set
        :raises: KeyError

        """
        ...

    def acquire_lock(
        self, item, session, value=..., cas=..., flags=...
    ) -> None:
        """Use Consul for locking by specifying the item/key to lock with
        and a session value for removing the lock.

        :param str item: The item in the Consul KV database
        :param str session: The session value for the lock
        :param mixed value: An optional value to set for the lock
        :param int cas: Optional Check-And-Set index value
        :param int flags: User defined flags to set
        :return: bool

        """
        ...

    def delete(self, item, recurse=...):
        """Delete an item from the Key/Value service

        :param str item: The item key
        :param bool recurse: Remove keys prefixed with the item pattern
        :raises: KeyError

        """
        ...

    def get(self, item, default=..., raw=...) -> None:
        """Get a value from the Key/Value service, returning it fully
        decoded if possible.

        :param str item: The item key
        :param mixed default: A default value to return if the get fails
        :param bool raw: Return the raw value from Consul
        :rtype: mixed
        :raises: KeyError

        """
        ...

    def get_record(self, item) -> None:
        """Get the full record from the Key/Value service, returning
        all fields including the flag.

        :param str item: The item key
        :rtype: dict
        :raises: KeyError

        """
        ...

    def find(
        self, prefix, separator=...
    ) -> list[dict[Any, Any]] | list[Any] | dict[Any, Any]:
        """Find all keys with the specified prefix, returning a dict of
        matches.

        *Example:*

        .. code:: python

            >>> consul.kv.find('b')
            {'baz': 'qux', 'bar': 'baz'}

        :param str prefix: The prefix to search with
        :rtype: dict

        """
        ...

    def items(self) -> list[dict[Any, Any]]:
        """Return a dict of all of the key/value pairs in the Key/Value service

         *Example:*

         .. code:: python

             >>> consul.kv.items()
             {'foo': 'bar', 'bar': 'baz', 'quz': True, 'corgie': 'dog'}

        :rtype: dict

        """
        ...

    def iteritems(self) -> Generator[tuple[Any, Any], Any, None]:
        """Iterate over the dict of key/value pairs in the Key/Value service

         *Example:*

         .. code:: python

             >>> for key, value in consul.kv.iteritems():
             ...     print(key, value)
             ...
             (u'bar', 'baz')
             (u'foo', 'bar')
             (u'quz', True)

        :rtype: iterator

        """
        ...

    def keys(self) -> list[Any]:
        """Return a list of all of the keys in the Key/Value service

        *Example:*

        .. code:: python

            >>> consul.kv.keys()
            [u'bar', u'foo', u'quz']

        :rtype: list

        """
        ...

    def records(self, key=...) -> list[tuple[Any, Any, Any]]:
        """Return a list of tuples for all of the records in the Key/Value
        service

        *Example:*

        .. code:: python

            >>> consul.kv.records()
            [(u'bar', 0, 'baz'),
             (u'corgie', 128, 'dog'),
             (u'foo', 0, 'bar'),
             (u'quz', 0, True)]

        :rtype: list of (Key, Flags, Value)

        """
        ...

    def release_lock(self, item, session) -> None:
        """Release an existing lock from the Consul KV database.

        :param str item: The item in the Consul KV database
        :param str session: The session value for the lock
        :return: bool

        """
        ...

    def set(self, item, value) -> None:
        """Set a value in the Key/Value service, using the CAS mechanism
        to ensure that the set is atomic. If the value passed in is not a
        string, an attempt will be made to JSON encode the value prior to
        setting it.

        :param str item: The key to set
        :param mixed value: The value to set
        :raises: KeyError

        """
        ...

    def set_record(self, item, flags=..., value=..., replace=...) -> None:
        """Set a full record, including the item flag

        :param str item: The key to set
        :param mixed value: The value to set
        :param replace: If True existing value will be overwritten:

        """
        ...

    def values(self) -> list[Any]:
        """Return a list of all of the values in the Key/Value service

        *Example:*

        .. code:: python

            >>> consul.kv.values()
            [True, 'bar', 'baz']

        :rtype: list

        """
        ...
