"""
This type stub file was generated by pyright.
"""

import contextlib

from consulate.api import base

"""
Lock Object for easy locking

"""
LOGGER = ...

class Lock(base.Endpoint):
    """Wrapper for easy :class:`~consulate.api.kv.KV` locks. Keys are
    automatically prefixed with ``consulate/locks/``. To change the prefix or
    remove it invoke the :meth:~consulate.api.lock.Lock.prefix` method.

    Example:

    .. code:: python

        import consulate

        consul = consulate.Consul()
        with consul.lock.acquire('my-key'):
            print('Locked: {}'.format(consul.lock.key))
            # Do stuff

    :raises: :exc:`~consulate.exception.LockError`

    """

    DEFAULT_PREFIX = ...
    def __init__(
        self, uri, adapter, session, datacenter=..., token=...
    ) -> None:
        """Create a new instance of the Lock

        :param str uri: Base URI
        :param consul.adapters.Request adapter: Request adapter
        :param consul.api.session.Session session: Session endpoint instance
        :param str datacenter: datacenter
        :param str token: Access Token

        """
        ...

    @contextlib.contextmanager
    def acquire(self, key=..., value=...) -> Generator[None, Any, None]:
        """A context manager that allows you to acquire the lock, optionally
        passing in a key and/or value.

        :param str key: The key to lock
        :param str value: The value to set in the lock
        :raises: :exc:`~consulate.exception.LockError`

        """
        ...

    @property
    def key(self) -> str | None:
        """Return the lock key

        :rtype: str

        """
        ...

    def prefix(self, value) -> None:
        """Override the path prefix for the lock key

        :param str value: The value to set the path prefix to

        """
        ...
