"""
This type stub file was generated by pyright.
"""

from consulate.api import base

"""
Consul Status Endpoint Access

"""

class Status(base.Endpoint):
    """Get information about the status of the Consul cluster. This are
    generally very low level, and not really useful for clients.

    """
    def leader(self) -> list[Any]:
        """Get the Raft leader for the datacenter the agent is running in.

        :rtype: str

        """
        ...

    def peers(self) -> list[Any]:
        """Get the Raft peers for the datacenter the agent is running in.

        :rtype: list

        """
        ...
